#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
