#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get update -y
sudo apt-get upgrade -y

sudo apt-get install haproxy -y
sudo sed -i -e "$aENABLED=1\n" /ect/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 125579-web-01 54.173.137.54:80 check\n\tserver 125579-web-02 100.25.21.165:80 check\n' /etc/haproxy/haproxy.cfg

service haproxy start
