#!/usr/bin/env bash
# configure nginx to run and listen on port 80


#printf %s "server {
#	listen 80 default_server;
#	listen [::]:80 default_server;
#}" >> /etc/nginx/nginx.conf

sudo service nginx start

sed -i '/^http {/a \    server {\n        listen 80 default_server;\n        listen [::]:80 default_server;\n    }' /etc/nginx/nginx.conf
