#!/usr/bin/env bash
# configure nginx to run and listen on port 80

rm /etc/nginx/sites-enbled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
